config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:destroy]
  resources :accounts, except: [:destroy]
  get '/home/show'
  root 'home#show'
  resources :sessions, only: [ :new, :create, :destroy ] 
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :supply_consumptions
  resources :supply_shipments
  resources :product_shipments
  resources :production_runs
  resources :suppliers
  resources :producers
  resources :customers
  resources :supplies
  resources :products
  resources :users
  resources :retail_shelves

end

app/models/production_run.rb
class ProductionRun < ActiveRecord::Base
  belongs_to :producer
  belongs_to :product
  validates :producer, presence: true
  validates :product, presence: true

  has_many :supply_consumptions, dependent: :destroy
  # A production run has many shipments. If no production run 
  # then no shipments.
  has_many :product_shipments, dependent: :destroy

  before_save :set_default
  validates :lot_name, presence: true, length: { maximum: 50 }
  validates :mfgd_amount, numericality: { only_interger: true, greater_than_or_equal_to: 0}, allow_blank: true


  def select_production_run(lot_name, product_id)
    ProductionRun.find_by(lot_name: lot_name, product_id: product_id)
  end

  private
  def set_default
    self.mfgd_amount ||= 0
  end
end

app/controllers/production_runs_controller.rb
class ProductionRunsController < ApplicationController
  before_action :signed_in_user
  before_action :set_production_run, only: [:show, :edit, :update, :destroy]

  # GET /production_runs
  # GET /production_runs.json
  def index
    @production_runs = ProductionRun.all.order(:mfgd_date)
  end

  # GET /production_runs/1
  # GET /production_runs/1.json
  def show
  end

  # GET /production_runs/new
  def new
    @production_run = ProductionRun.new
  end

  # GET /production_runs/1/edit
  def edit
  end

  # POST /production_runs
  # POST /production_runs.json
  def create
    @production_run = ProductionRun.new(production_run_params)

    respond_to do |format|
      if @production_run.save
        format.html { redirect_to @production_run, notice: 'Production run was successfully created.' }
        format.json { render :show, status: :created, location: @production_run }
      else
        format.html { render :new }
        format.json { render json: @production_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /production_runs/1
  # PATCH/PUT /production_runs/1.json
  def update
    respond_to do |format|
      if @production_run.update(production_run_params)
        format.html { redirect_to @production_run, notice: 'Production run was successfully updated.' }
        format.json { render :show, status: :ok, location: @production_run }
      else
        format.html { render :edit }
        format.json { render json: @production_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /production_runs/1
  # DELETE /production_runs/1.json
  def destroy
    @production_run.destroy
    respond_to do |format|
      format.html { redirect_to production_runs_url, notice: 'Production run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_production_run
      @production_run = ProductionRun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def production_run_params
      params.require(:production_run).permit(:lot_name, :producer_id, :product_id, :mfgd_amount, :mfgd_date, :expiry_date)
    end
end

app/views/production_runs/_form.html.erb
<%= form_for @production_run, :html => { :class => "form-horizontal production_run" } do |f| %>

  <% if @production_run.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@production_run.errors.count, "error") %> prohibited this production_run from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @production_run.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :lot_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lot_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lot_name) %>
  </div>
  <div class="form-group">
    <%= f.label :invoice_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :invoice_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:invoice_number) %>
  </div>
  <div class="form-group">
    <%= f.label :product_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= collection_select(:production_run, :product_id, Product.all, :id, :name,
          {:prompt => 'Please select the product name'}) %>
    </div>
    <%=f.error_span(:product_id) %>
  </div>
  <div class="form-group">
    <%= f.label :producer_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= collection_select(:production_run, :producer_id, Producer.all, :id, :name,
        {prompt: "Please select the production run" }) %>
    </div>
    <%=f.error_span(:producer_id) %>
  </div>
  <div class="form-group">
    <%= f.label :mfgd_amount, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mfgd_amount, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mfgd_amount) %>
  </div>
  <div class="form-group">
    <%= f.label :mfgd_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :mfgd_date, :order => [:month, :day, :year], :class => 'form-control' %>
    </div>
    <%=f.error_span(:mfgd_date) %>
  </div>
  <div class="form-group">
    <%= f.label :expiry_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :expiry_date, :order => [:month, :day, :year], :class => 'form-control' %>
    </div>
    <%=f.error_span(:expiry_date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                production_runs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/production_runs/edit.html.erb
<%- model_class = ProductionRun -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/production_runs/index.html.erb
<%- model_class = ProductionRun -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_production_run_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:lot_name) %></th>
      <th>Invoice#</th>
      <th><%= model_class.human_attribute_name(:producer_id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:mfgd_amount) %></th>
      <th><%= model_class.human_attribute_name(:mfgd_date) %></th>
      <th><%= model_class.human_attribute_name(:expiry_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @production_runs.each do |production_run| %>
      <tr>
        <td><%= link_to production_run.lot_name, production_run_path(production_run) %></td>
        <td><%= production_run.invoice_number %></td>
        <td><%= production_run.producer.name %></td>
        <td><%= production_run.product.name %></td>
        <td><%= pluralize production_run.mfgd_amount, production_run.product.unit%></td>
        <td><%= production_run.mfgd_date.to_s(:long) if production_run.mfgd_date %></td>
        <td><%= production_run.expiry_date.to_s(:long) if production_run.expiry_date %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_production_run_path(production_run), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      production_run_path(production_run),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/production_runs/new.html.erb
<%- model_class = ProductionRun -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/production_runs/show.html.erb
<%- model_class = ProductionRun -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="container">
<div class="row">
<div class="col-md-4">
<table class="table">
  <tbody>
    <tr>
      <td><strong>Lot Name</strong></td>
      <td><%=@production_run.lot_name%></td>
    </tr>
    <tr>
      <td><strong>Invoice#</strong></td>
      <td><%=@production_run.invoice_number%></td>
    </tr>
    <tr>
      <td><strong>Product</strong></td>
      <td><%=@production_run.product.name%></td>
    </tr>
    <tr>
      <td><strong>Producer</strong></td>
      <td><%=link_to @production_run.producer.name, producers_path(@production_run.producer)%></td>
    </tr>
    <tr>
      <td><strong>Mfgd Amount</strong></td>
      <td><%= pluralize @production_run.mfgd_amount, @production_run.product.unit%></td>
    </tr>
    <tr>
      <td><strong>Mfgd Date</strong></td>
      <td><%= @production_run.mfgd_date.to_s(:long) if @production_run.mfgd_date%></td>
    </tr>
    <tr>
      <td><strong>Expiry Date</strong></td>
      <td><%= @production_run.expiry_date.to_s(:long) if @production_run.expiry_date %></td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              production_runs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_production_run_path(@production_run), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              production_run_path(@production_run),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<h3 class="display-1">Shipment From <%=@production_run.lot_name%> </h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>Order Amount</th>
      <th>Return Amount</th>
      <th>Ship Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @production_run.product_shipments.each do |prod_shipment| %>
    <tr>
      <td><%= prod_shipment.customer.name %></td>
      <td><%= pluralize prod_shipment.order_amount, prod_shipment.production_run.product.unit %></td>
      <td><%= pluralize prod_shipment.return_amount, prod_shipment.production_run.product.unit %></td>
      <td><%= prod_shipment.ship_date.to_s(:long)%></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_shipment_path(prod_shipment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_shipments_path(prod_shipment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <%end%>
  </tbody>
</table>

<h3 class="display-1">Supplies Used By <%=@production_run.lot_name%></h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Supply Name</th>
      <th>Used Amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @production_run.supply_consumptions.each do |supply_consumption| %>
    <tr>
      <td><%= supply_consumption.supply.name %></td>
      <td><%= pluralize supply_consumption.used_amount, supply_consumption.supply.unit%></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_supply_consumption_path(supply_consumption), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      supply_consumption_path(supply_consumption),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <%end%>
  </tbody>
</table>