config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:destroy]
  resources :accounts, except: [:destroy]
  get '/home/show'
  root 'home#show'
  resources :sessions, only: [ :new, :create, :destroy ] 
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :supply_consumptions
  resources :supply_shipments
  resources :product_shipments
  resources :production_runs
  resources :suppliers
  resources :producers
  resources :customers
  resources :supplies
  resources :products
  resources :users
  resources :retail_shelves

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :signed_in_user
  def show
    @products = Product.all
    @supplies = Supply.all
    @customer_shipments = []
    @customers = Customer.all
    Struct.new("CustomerShipment", :name, :address, :total_order_amount)
    @customers.each do |customer|
      total_order_amount = ProductShipment.total_order_amount(customer.id)
      if total_order_amount > 0
        @customer_shipments.push(
              Struct::CustomerShipment.new(customer.name, customer.address, total_order_amount))
      end
      @customer_shipments.sort! do |a, b|
        b.total_order_amount <=> a.total_order_amount
      end
    end
  end
end

app/views/home/show.html.erb
<h1>Dashboard</h1>
<div class="panel panel-primary">
  <div class="panel-heading">Product Inventory</div>
  <div class="panel-body">
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Amount Left</th>
      <th>Amount Produced</th>
      <th>Amount Shipped</th>
      <th>Amount Return</th>
      <th>Comments</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%=link_to product.name, product_path(product)%></td>
      <td><%= pluralize product.left_amount, product.unit%></td>
      <td><%= pluralize product.total_produced, product.unit%></td>
      <td><%= pluralize product.total_shipments, product.unit%></td>
      <td><%= pluralize product.total_returns, product.unit%></td>
      <td><%= product.adjust_to_comment%></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<div class="panel panel-info">
  <div class="panel-heading">Supplies Inventory</div>
  <div class="panel-body">
<table class="table table-bordered table-stripped table-hover">
  <thead>
    <tr>
      <th>Supply</th>
      <th>Amount Left</th>
      <th>Amount Rcvd</th>
      <th>Amount Consumed</th>
      <th>Amount Adjust</th>
    </tr>
  </thead>

  <tbody>
    <% @supplies.each do |supply| %>
    <tr>
      <td><%=link_to supply.name, supply_path(supply)%></td>
      <td><%= pluralize supply.left_amount, supply.unit %></td>
      <td><%= pluralize supply.total_orders,  supply.unit %></td>
      <td><%=  pluralize supply.total_consumptions, supply.unit%></td>
      <td><%=  pluralize supply.adjust, supply.unit%></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="panel panel-info">
  <div class="panel-heading">Customer Shipments</div>
  <div class="panel-body">
<table class="table table-bordered table-stripped table-hover">
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>Customer Address</th>
      <th>Total Products Shipped</th>
    </tr>
  </thead>

  <tbody>
    <% @customer_shipments.each do |shipment| %>
    <tr>
      <td><%= shipment.name %></td>
      <td><%= shipment.address %></td>
      <td><%= pluralize shipment.total_order_amount, "bottle" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>