config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:destroy]
  resources :accounts, except: [:destroy]
  get '/home/show'
  root 'home#show'
  resources :sessions, only: [ :new, :create, :destroy ] 
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :supply_consumptions
  resources :supply_shipments
  resources :product_shipments
  resources :production_runs
  resources :suppliers
  resources :producers
  resources :customers
  resources :supplies
  resources :products
  resources :users
  resources :retail_shelves

end

app/models/producer.rb
class Producer < ActiveRecord::Base

  before_validation { |producer| producer.unique_name = name.downcase.gsub(/\s+/, "") }
  validates :unique_name, presence: true, uniqueness: true, length: { maximum: 50 }

  # A producer has many production runs. 
  has_many :production_runs, dependent: :destroy

end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :signed_in_user
  before_action :set_producer, only: [:show, :edit, :update, :destroy]

  # GET /producers
  # GET /producers.json
  def index
    @producers = Producer.all
  end

  # GET /producers/1
  # GET /producers/1.json
  def show
  end

  # GET /producers/new
  def new
    @producer = Producer.new
  end

  # GET /producers/1/edit
  def edit
  end

  # POST /producers
  # POST /producers.json
  def create
    @producer = Producer.new(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to @producer, notice: 'Producer was successfully created.' }
        format.json { render :show, status: :created, location: @producer }
      else
        format.html { render :new }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producers/1
  # PATCH/PUT /producers/1.json
  def update
    respond_to do |format|
      if @producer.update(producer_params)
        format.html { redirect_to @producer, notice: 'Producer was successfully updated.' }
        format.json { render :show, status: :ok, location: @producer }
      else
        format.html { render :edit }
        format.json { render json: @producer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producers/1
  # DELETE /producers/1.json
  def destroy
    @producer.destroy
    respond_to do |format|
      format.html { redirect_to producers_url, notice: 'Producer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producer
      @producer = Producer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producer_params
      params.require(:producer).permit(:name, :contact_name, :address, :email, :phone)
    end
end

app/views/producers/_form.html.erb
<%= form_for @producer, :html => { :class => "form-horizontal producer" } do |f| %>

  <% if @producer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@producer.errors.count, "error") %> prohibited this producer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @producer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :contact_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :contact_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:contact_name) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                producers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/producers/edit.html.erb
<%- model_class = Producer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/producers/index.html.erb
<%- model_class = Producer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:contact_name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @producers.each do |producer| %>
      <tr>
        <td><%= link_to producer.name, producer_path(producer) %></td>
        <td><%= producer.contact_name %></td>
        <td><%= producer.address %></td>
        <td><%= producer.email %></td>
        <td><%= producer.phone %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_producer_path(producer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      producer_path(producer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_producer_path,
            :class => 'btn btn-primary' %>

app/views/producers/new.html.erb
<%- model_class = Producer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/producers/show.html.erb
<%- model_class = Producer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="container">
<div class="row">
<div class="col-md-4">
<table class="table">
  <tbody>
    <tr>
      <td><strong>Name</strong></td>
      <td><%=@producer.name%></td>
    </tr>
    <tr>
      <td><strong>Contact Name</strong></td>
      <td><%=@producer.contact_name%></td>
    </tr>
    <tr>
      <td><strong>Address</strong></td>
      <td><%=@producer.address%></td>
    </tr>
    <tr>
      <td><strong>Email</strong></td>
      <td><%=@producer.email%></td>
    </tr>
    <tr>
      <td><strong>Phone</strong></td>
      <td><%=@producer.phone%></td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              producers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_producer_path(@producer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              producer_path(@producer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

<h3 class="display-1">Production Run By <%=@producer.name%></h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Lot Name</th>
      <th>Product</th>
      <th>Mfgd Amount</th>
      <th>Mfgd Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @producer.production_runs.each do |prod_run| %>
    <tr>
      <td><%= prod_run.lot_name %></td>
      <td><%= prod_run.product.name %></td>
      <td><%= prod_run.mfgd_amount%></td>
      <td><%= prod_run.mfgd_date.to_s(:long)%></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_production_run_path(prod_run), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      production_runs_path(prod_run),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <%end%>
  </tbody>
</table>